// Isolated account restoration QA; run with account_visibility_browser_server.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/ForestHill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const base = 'http://127.0.0.1:43260';
const evidence = path.resolve('.scratch/account-management-followup/evidence/accounts');
const headers = { Authorization: 'Bearer ticket-16-browser' };
(async () => {
  await fs.mkdir(evidence, { recursive: true });
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, acceptDownloads: true });
    await context.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort());
    const page = await context.newPage();
    const errors = [];
    let saves = 0;
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (request.url().endsWith('/api/accounts/move')) saves++; });
    page.setDefaultTimeout(10000);
    const row = letter => page.locator('tbody tr').filter({ hasText: `${letter}@example.test` });
    const order = expected => page.waitForFunction(expected => Array.from(document.querySelectorAll('tbody tr')).map(row => row.cells[5].textContent.trim()).join(',') === expected, expected.map(letter => `${letter}@example.test`).join(','));
    const saved = () => page.getByText('组内顺序已保存', { exact: true }).first().waitFor();
    const login = async target => {
      await target.goto(`${base}/login/`);
      await target.getByLabel('密钥', { exact: true }).fill('ticket-16-browser');
      await target.getByRole('button', { name: '登录', exact: true }).click();
      await target.waitForURL('**/accounts/');
    };
    const drag = async (source, target) => {
      const from = await row(source).getByRole('button', { name: `排序 ${source}@example.test`, exact: true }).boundingBox();
      const to = await row(target).boundingBox();
      const sourceRow = await row(source).boundingBox();
      await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
      await page.mouse.down();
      await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2 + (to.y - sourceRow.y) * 0.35, { steps: 8 });
      await page.waitForTimeout(50);
      assert.notEqual(await row(source).evaluate(el => getComputedStyle(el).transform), 'none', 'dragged row must follow the pointer between slots');
      await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2 + to.y - sourceRow.y, { steps: 12 });
    };
    await login(page);
    await order(['m', 'n', 'a', 'b', 'd']);
    assert.equal(await page.getByRole('checkbox', { name: /显示隐藏/ }).count(), 0);
    const downloadReady = page.waitForEvent('download');
    await page.getByRole('button', { name: '导出全部账号（JSON）', exact: true }).click();
    const exported = JSON.parse(await fs.readFile(await (await downloadReady).path(), 'utf8'));
    assert.equal(exported.length, 5);
    const before = saves;
    await drag('n', 'm');
    await order(['n', 'm', 'a', 'b', 'd']);
    assert.equal(saves, before, 'preview must precede saving');
    await page.screenshot({ path: path.join(evidence, 'drag-preview.png'), fullPage: true });
    await page.mouse.up();
    await saved();
    await page.reload();
    await order(['n', 'm', 'a', 'b', 'd']);
    await page.route('**/api/accounts/move', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ detail: { error: 'controlled save failure' } }) }), { times: 1 });
    await drag('m', 'n');
    await order(['m', 'n', 'a', 'b', 'd']);
    await page.mouse.up();
    await order(['n', 'm', 'a', 'b', 'd']);
    await page.getByText('controlled save failure', { exact: true }).waitFor();
    const sameSaves = saves;
    await drag('a', 'm');
    await page.mouse.up();
    await order(['n', 'm', 'a', 'b', 'd']);
    assert.equal(saves, sameSaves, 'cross-group drag must not save');
    const handle = row('a').getByRole('button', { name: '排序 a@example.test', exact: true });
    await handle.focus();
    await handle.press('ArrowDown');
    await order(['n', 'm', 'b', 'a', 'd']);
    assert.equal(await handle.evaluate(el => el === document.activeElement), true);
    assert.equal((await context.request.post(`${base}/qa/rotate`, { headers })).status(), 200);
    assert.equal((await context.request.post(`${base}/qa/reload`, { headers })).status(), 200);
    await page.reload();
    await order(['n', 'm', 'b', 'a', 'd']);
    assert.match(await row('m').textContent(), /qa-m-rotated/);
    await row('d').getByRole('button', { name: '删除账号', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: '确认删除', exact: true }).click();
    await order(['n', 'm', 'b', 'a']);
    await page.screenshot({ path: path.join(evidence, 'restored-accounts.png'), fullPage: true });
    const narrow = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
    await narrow.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.abort());
    const mobile = await narrow.newPage();
    await login(mobile);
    const first = mobile.getByRole('button', { name: '排序 n@example.test', exact: true });
    await first.focus();
    await first.press('ArrowDown');
    await mobile.waitForFunction(() => document.querySelector('tbody tr')?.textContent.includes('m@example.test'));
    await mobile.screenshot({ path: path.join(evidence, 'narrow-reduced-motion.png'), fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: all accounts visible, JSON export, live drag preview, save rollback, group guard, keyboard focus, token rotation, explicit disabled-account deletion, reduced-motion mobile.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
