// Both layouts contain 3,200 real PNGs across two conversations; all services are controlled.
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chromium } = require('C:/Users/ForestHill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const origin = 'http://127.0.0.1:43290';
const dense = process.env.TICKET13_DENSE === '1', rounds = dense ? 16 : 80;
const output = path.resolve('.scratch/account-management-followup/evidence/all-rounds', dense ? 'dense' : 'normal');
const headers = {Authorization:'Bearer ticket13-A'};
const pause = ms => new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 await fs.mkdir(output,{recursive:true});
 const browser = await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const context = await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
 await context.addInitScript(()=>{
  window.blobs={live:new Set(),peak:0,revoked:0};
  const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);
  URL.createObjectURL=blob=>{const url=create(blob);window.blobs.live.add(url);window.blobs.peak=Math.max(window.blobs.peak,window.blobs.live.size);return url;};
  URL.revokeObjectURL=url=>{window.blobs.live.delete(url);window.blobs.revoked++;revoke(url);};
 });
 const page=await context.newPage();page.setDefaultTimeout(30000);
 const metrics={}, errors=[], details=[], queries=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(r.url().endsWith('/api/image-tasks/query'))queries.push(r.postDataJSON().ids.length);});
 page.on('response',async r=>{if(/\/api\/image-conversations\/gallery-\d+\?/.test(r.url())&&!r.url().includes('navigation=true')){try{const body=await r.json();details.push({url:r.url(),turns:body.turns?.length});}catch{}}});
 const viewport=page.locator('.hide-scrollbar.overflow-y-auto');
 const nav=()=>page.getByRole('navigation',{name:'结果定位导航'}).filter({visible:true});
 const group=n=>nav().locator(`[data-navigation-source="gallery-0-source-${String(n).padStart(3,'0')}"]`);
 const ready=()=>page.waitForFunction(()=>{
  const root=document.querySelector('.hide-scrollbar.overflow-y-auto');if(!root)return false;
  const bounds=root.getBoundingClientRect();
  const frames=[...root.querySelectorAll('[data-image-frame]')].filter(e=>{const r=e.getBoundingClientRect();return r.top<bounds.bottom&&r.bottom>bounds.top;});
  return frames.length&&frames.every(e=>{const img=e.querySelector('img');return img?.complete&&img.naturalWidth===480;});
 });
 const all=async(id='gallery-0')=>{await page.waitForFunction(({id,rounds})=>document.querySelectorAll(`[data-turn-id^="${id}-turn-"]`).length===rounds,{id,rounds});await ready();};
 const aligned=async id=>{await ready();await page.waitForFunction(id=>{
  const item=document.querySelector(`[data-image-id="${id}"]`),root=document.querySelector('.hide-scrollbar.overflow-y-auto');
  return item&&Math.abs(item.getBoundingClientRect().top-root.getBoundingClientRect().top)<3;
 },id);};
 const login=async(p,key='ticket13-A')=>{await p.goto(origin+'/login/');await p.getByLabel('密钥',{exact:true}).fill(key);await p.getByRole('button',{name:'登录',exact:true}).click();await p.waitForURL('**/accounts/');await p.goto(origin+'/image/');};
 try{
  await context.request.put(origin+'/api/image-conversations/current',{headers,data:{conversation_id:'gallery-0'}});
  const started=Date.now();await login(page);await all();await group(0).waitFor();
  metrics.first_open_and_login_ms=Date.now()-started;
  assert.equal(await page.locator('[data-image-id]').count(),1600);
  assert.equal(await page.getByLabel('结果分页').count(),0);
  metrics.initial_blobs=await page.evaluate(()=>window.blobs.live.size);assert(metrics.initial_blobs<80);
  assert.equal(await nav().locator('[data-navigation-source]').count(),8);
  await group(0).getByRole('button',{name:'展开或收起 SUB00 · MD item 0',exact:true}).click();
  assert.equal(await group(0).getByRole('button',{name:/次 · \d+ 张/}).count(),dense?2:10);
  assert.equal(await nav().locator('[data-navigation-image]').count(),0);
  const target='gallery-0-turn-000-0';const readsBefore=details.length;
  const firstRound=group(0).getByRole('button',{name:/^第 1 次 ·/});
  await firstRound.click();await ready();
  await page.waitForFunction(()=>{const turn=document.querySelector('[data-turn-id="gallery-0-turn-000"]'),root=document.querySelector('.hide-scrollbar.overflow-y-auto');return Math.abs(turn.getBoundingClientRect().top-root.getBoundingClientRect().top)<3;});
  await viewport.evaluate(root=>{const image=root.querySelector('[data-image-id="gallery-0-turn-000-0"]');root.scrollTop+=image.getBoundingClientRect().top-root.getBoundingClientRect().top;});await aligned(target);
  assert.equal(details.length,readsBefore,'In-memory navigation needs no new detail read');
  const title=`All rounds refreshed ${Date.now()}`;
  await context.request.patch(origin+'/api/image-conversations/gallery-0',{headers,data:{title}});
  await page.getByRole('button',{name:new RegExp(title)}).waitFor();await all();await aligned(target);
  await viewport.evaluate(e=>{e.firstElementChild.firstElementChild.style.paddingTop='40px';});await aligned(target);
  await viewport.evaluate(e=>{e.firstElementChild.firstElementChild.style.paddingTop='';});await aligned(target);
  metrics.polling_keeps_all_rounds_and_target=true;
  const top=await viewport.evaluate(e=>e.scrollTop);
  await group(0).getByRole('button',{name:'展开或收起 SUB00 · MD item 0',exact:true}).click();
  assert.equal(await viewport.evaluate(e=>e.scrollTop),top);
  await group(0).getByRole('button',{name:/^SUB00 · MD item 0/}).click();
  const latest=dense?'008':'072', manual=`gallery-0-turn-${latest}-12`;
  await page.waitForFunction(tid=>{const e=document.querySelector(`[data-turn-id="${tid}"]`),r=document.querySelector('.hide-scrollbar.overflow-y-auto');return e&&Math.abs(e.getBoundingClientRect().top-r.getBoundingClientRect().top)<3;},`gallery-0-turn-${latest}`);
  await viewport.evaluate((root,id)=>{const e=root.querySelector(`[data-image-id="${id}"]`);root.scrollTop+=e.getBoundingClientRect().top-root.getBoundingClientRect().top;},manual);await ready();
  await page.waitForFunction(()=>[...document.querySelectorAll('[data-navigation-source]')].some(e=>/当前位置.*图片 13/.test(e.textContent)));
  const manualScroll=await viewport.evaluate(e=>e.scrollTop);
  await page.setViewportSize({width:1420,height:1000});await ready();assert.equal(await viewport.evaluate(e=>e.scrollTop),manualScroll);
  await page.setViewportSize({width:1440,height:1000});await ready();metrics.manual_scroll_stable=true;
  metrics.scroll_frames=await viewport.evaluate(async root=>{const times=[];let prior=performance.now();for(let n=0;n<90;n++){root.scrollTop=root.scrollHeight*n/89;await new Promise(requestAnimationFrame);const now=performance.now();times.push(now-prior);prior=now;}times.sort((a,b)=>a-b);return {p95_ms:times[Math.floor(times.length*.95)],max_ms:times.at(-1)};});
  await ready();await page.locator('textarea').fill('All 1,600 current results remain usable');
  await page.screenshot({path:path.join(output,'all-rounds-desktop.png')});
  let release,entered,held=false;const waiting=new Promise(resolve=>entered=resolve);
  await page.route('**/api/image-conversations/gallery-1?*',async route=>{if(held)return route.continue();held=true;const response=await route.fetch();const gate=new Promise(resolve=>release=resolve);entered();await gate;await route.fulfill({response});});
  await page.getByRole('button',{name:/Large gallery 1/}).click();await waiting;
  await page.getByRole('button',{name:new RegExp(title)}).click();release();await all();await pause(300);
  assert.equal(await page.locator('[data-turn-id^="gallery-1-turn-"]').count(),0);await page.unroute('**/api/image-conversations/gallery-1?*');
  await page.getByRole('button',{name:/Large gallery 1/}).click();await all('gallery-1');
  assert.equal(await page.locator('[data-image-id]').count(),1600);
  await page.getByRole('button',{name:new RegExp(title)}).click();await all();metrics.switch_race_safe=true;
  const second=await browser.newContext({viewport:{width:1440,height:1000}});const other=await second.newPage();await login(other);
  await other.waitForFunction(rounds=>document.querySelectorAll('[data-turn-id]').length===rounds,rounds);await second.close();
  assert.equal((await context.request.get(origin+'/api/image-conversations/gallery-0',{headers:{Authorization:'Bearer ticket13-B'}})).status(),404);
  await page.setViewportSize({width:320,height:360});await page.getByRole('button',{name:'定位',exact:true}).click();
  const dialog=page.getByRole('dialog');await dialog.getByRole('navigation').evaluate(e=>e.scrollTop=e.scrollHeight);await dialog.getByRole('button',{name:/^Source 7/}).click();
  await page.locator('.image-result-panel').scrollIntoViewIfNeeded();await ready();await page.screenshot({path:path.join(output,'all-rounds-small.png')});
  await page.getByRole('button',{name:/自动.*张/}).click();const count=page.getByRole('spinbutton',{name:'生成数量',exact:true});await count.scrollIntoViewIfNeeded();
  assert(await count.evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;}));await count.fill('7');
  await page.getByRole('button',{name:/自动.*张/}).click();await page.setViewportSize({width:1440,height:1000});
  assert.equal((await context.request.delete(origin+'/api/image-conversations/gallery-0/turns/gallery-0-turn-000/images/gallery-0-turn-000-9',{headers})).status(),200);
  await page.waitForFunction(()=>!document.querySelector('[data-image-id="gallery-0-turn-000-9"]'));
  assert.equal((await context.request.patch(origin+'/api/image-conversations/gallery-0',{headers,data:{turns:[{id:'gallery-0-turn-000',promptDeleted:true,resultsDeleted:true}]}})).status(),200);
  await page.waitForFunction(()=>{const turn=document.querySelector('[data-turn-id="gallery-0-turn-000"]');return turn?.textContent.includes('提示词已删除')&&!turn.querySelector('[data-image-id]');});
  const navigation=await context.request.get(origin+'/api/image-conversations/gallery-0?navigation=true&offset=0&limit=10',{headers});
  assert(!(await navigation.json()).turns.some(turn=>turn.id==='gallery-0-turn-000'));
  metrics.deletion_refresh_safe=true;
  metrics.blobs=await page.evaluate(()=>({live:window.blobs.live.size,peak:window.blobs.peak,revoked:window.blobs.revoked}));
  assert(metrics.blobs.peak<80);assert(details.length>0&&details.every(d=>d.turns<=10));
  assert(queries.length>=8&&queries.every(n=>n<=200));metrics.detail_reads=details.length;metrics.max_task_query=Math.max(...queries);
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(output,'metrics.json'),JSON.stringify(metrics,null,2));console.log(JSON.stringify(metrics));
 }catch(error){await page.screenshot({path:path.join(output,'failure.png')});throw error;}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
