const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chromium } = require('C:/Users/ForestHill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const origin = 'http://127.0.0.1:43280';
const headers = { Authorization: 'Bearer ticket08-A' };
const output = path.resolve('.scratch/account-management-followup/evidence/image-ui');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(check, label='state') { for (let n=0;n<250;n++) { if(await check()) return; await pause(80); } throw Error(`Timed out: ${label}`); }
(async () => {
 await fs.mkdir(output,{recursive:true});
 const browser = await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try {
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  await context.route('**/*', route => new URL(route.request().url()).origin===origin ? route.continue() : route.abort());
  await context.addInitScript(() => localStorage.setItem('chatgpt2api:md_counts', JSON.stringify({P01:'9'})));
  const get = async url => { const r=await context.request.get(origin+url,{headers}); assert.equal(r.status(),200); return r.json(); };
  const post = async (url,data={}) => { const r=await context.request.post(origin+url,{headers,data}); assert.equal(r.status(),200,await r.text()); return r.json(); };
  const initial = await post('/api/image-conversations/turns',{request_id:'existing',prompt:'Existing history',count:1});
  const page=await context.newPage(); const errors=[]; const batches=[]; let created=0;
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{ if(r.url()===origin+'/api/image-conversations'&&r.method()==='POST') created++; if(r.url().endsWith('/api/image-imports/batches')) batches.push(r.postDataJSON()); });
  const login=async p=>{await p.goto(origin+'/login/');await p.getByLabel('密钥',{exact:true}).fill('ticket08-A');await p.getByRole('button',{name:'登录',exact:true}).click();await p.waitForURL('**/accounts/');await p.goto(origin+'/image/');};
  await login(page); await page.locator('[data-turn-id]').first().waitFor();
  await page.getByRole('button',{name:'新建对话',exact:true}).click();
  await pause(2300);
  assert.equal((await get('/api/image-conversations')).pagination.total,1);
  assert.equal(await page.locator('[data-turn-id]').count(),0);
  assert.equal(created,0);
  await page.locator('textarea').fill('Fresh draft first submission');
  const accepted=page.waitForResponse(r=>r.url().endsWith('/api/image-conversations/turns')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'生成图片',exact:true}).click();
  const fresh=await (await accepted).json(); assert.notEqual(fresh.id,initial.id);
  await until(async()=>await page.locator('[data-turn-id]').count()===1,'new conversation selected');
  for(let n=0;n<12;n++) await post('/api/image-conversations/turns',{request_id:`extra-${n}`,conversation_id:fresh.id,prompt:`Extra round ${n}`,count:1});
  await until(async()=>await page.locator('[data-turn-id]').count()===13,'all 13 rounds without paging');
  assert.equal(await page.getByRole('button',{name:'较早结果',exact:true}).count(),0);
  await page.screenshot({path:path.join(output,'all-rounds.png')});
  await page.getByRole('button',{name:'新建对话',exact:true}).click();
  await page.getByRole('button',{name:'上传 MD 和参考图',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'导入 Prompt 包',exact:true});
  await until(()=>dialog.getByRole('button',{name:/选择或拖入 Markdown/}).isEnabled());
  const titles=['白底主图','双人套装与晨间用餐','缺少参考图','人物手持与表面细节','三种餐具与多样食物','家中咖啡馆氛围','尺寸与套装内容'];
  const md=titles.map((title,n)=>`## [P0${n+1}] ${title}｜1600x1600\n参考图：${n===0?'main.png':n===2?'missing.png':n===6?'slow.png':'无'}\n### Prompt\n~~~\nSynthetic item ${n+1}\n~~~`).join('\n');
  await page.getByLabel('选择 MD 文件',{exact:true}).setInputFiles({name:'01_主图与副图_一体式Prompts.md',mimeType:'text/markdown',buffer:Buffer.from(md)});
  await until(async()=>await dialog.getByRole('article').count()===7);
  const png=await fs.readFile(path.resolve('data/ticket08/reference.png'));
  await page.getByLabel('选择导入参考图',{exact:true}).setInputFiles([{name:'main.png',mimeType:'image/png',buffer:png},{name:'unused.png',mimeType:'image/png',buffer:png}]);
  await until(async()=>(await get('/api/image-imports')).candidates[0].status==='ready');
  await page.getByLabel('选择导入参考图',{exact:true}).setInputFiles(path.resolve('data/ticket08/slow.png'));
  await until(async()=>(await get('/ticket08-state')).upload_entered);
  await until(async()=>(await get('/api/image-imports')).candidates[6].status==='pending');
  await dialog.getByText('单条 9 张',{exact:true}).waitFor();
  await page.getByLabel('批量生成数量',{exact:true}).fill('2');
  assert.equal(await page.getByLabel('P01 单条数量',{exact:true}).inputValue(),'');
  const second=dialog.getByRole('article',{name:'条目 P02 双人套装与晨间用餐',exact:true});
  await second.locator('summary').first().click();
  await second.getByLabel('P02 单条数量',{exact:true}).fill('3');
  await second.locator('summary').first().click();
  await dialog.getByText('单条 3 张',{exact:true}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-sonner-toast]'));
  await page.screenshot({path:path.join(output,'prompt-import-desktop.png')});
  let lost=false;
  await page.route('**/api/image-imports/batches',async route=>{const response=await route.fetch();lost=true;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:{error:'controlled lost response'}})});},{times:1});
  await dialog.getByRole('button',{name:'生成已选条目（13 张）',exact:true}).click();
  await until(()=>Promise.resolve(lost));
  await dialog.getByRole('button',{name:'重试上次提交（13 张）',exact:true}).waitFor();
  await page.getByLabel('批量生成数量',{exact:true}).fill('1');
  await dialog.getByRole('button',{name:'重试上次提交（13 张）',exact:true}).click();
  await dialog.getByRole('status').filter({hasText:'已接受'}).waitFor();
  assert.equal(batches.length,2); assert.deepEqual(batches[0],batches[1]); assert(batches[0].draft_id); assert.equal(batches[0].conversation_id,null);
  assert.deepEqual(batches[0].entries.map(e=>e.count??batches[0].count),[2,3,2,2,2,2]);
  await post('/ticket08-release-upload');
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  await until(async()=>await page.locator('[data-turn-id]').count()===6,'MD draft accepted');
  assert.equal((await get('/api/image-conversations')).pagination.total,3);
  await page.getByRole('button',{name:'上传 MD 和参考图',exact:true}).click();
  await page.setViewportSize({width:320,height:360}); await pause(300);
  await page.waitForFunction(()=>!document.querySelector('[data-sonner-toast]'));
  await page.screenshot({path:path.join(output,'prompt-import-small.png')});
  const box=await dialog.getByRole('button',{name:/生成已选条目/}).boundingBox(); assert(box.y>=0&&box.y+box.height<=360&&box.x>=0&&box.x+box.width<=320);
  await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  await post('/followup-seed-cleanups');
  await page.getByRole('button',{name:/^删除清理/}).click();
  const cleanup=page.getByRole('dialog',{name:'删除清理',exact:true});
  await cleanup.getByRole('button',{name:/一键重试所有失败项.*55/}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-sonner-toast]'));
  await page.screenshot({path:path.join(output,'cleanup-small.png')});
  const next=await cleanup.getByRole('button',{name:'下一页',exact:true}).boundingBox(); assert(next.y+next.height<=360,'cleanup footer visible at 320x360');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:path.join(output,'cleanup-desktop.png')});
  await cleanup.getByRole('button',{name:/一键重试所有失败项.*55/}).click();
  await until(async()=>(await get('/api/image-cleanups')).stats.complete===55,'all cleanup pages');
  assert.deepEqual(errors,[]);
  console.log('PASS: local draft only, full 13 rounds, compact imports, visible/reset overrides, pending uploads accepted, idempotent lost-response retry, 320x360 controls, all-page cleanup.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
